-- =============================================================================
-- Migración: sistema de notificaciones Web Push para la PWA de Stratos
-- =============================================================================
-- Permite que las notificaciones lleguen con la app CERRADA en iPhone/Android
-- cuando el usuario instaló la PWA ("Agregar a inicio").
--
-- Tabla: push_subscriptions
--   Guarda los endpoints de push de cada dispositivo + usuario.
--   Un mismo usuario puede tener varios dispositivos (iPhone, PC, tablet).
--
-- RPCs:
--   push_subscribe    → registra una suscripción nueva (o actualiza existente)
--   push_unsubscribe  → elimina la suscripción de un usuario
--   push_get_for_user → devuelve las suscripciones de un usuario (para enviar)
-- =============================================================================

-- 1. Tabla de suscripciones push
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint    text NOT NULL,
  p256dh      text NOT NULL,
  auth        text NOT NULL,
  platform    text DEFAULT 'other',  -- ios, android, macos, windows, other
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  UNIQUE(user_id, endpoint)  -- misma suscripción no se duplica
);

-- RLS: cada usuario solo ve y modifica sus propias suscripciones
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios ven sus propias suscripciones"
  ON public.push_subscriptions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Los usuarios gestionan sus propias suscripciones"
  ON public.push_subscriptions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Los usuarios actualizan sus propias suscripciones"
  ON public.push_subscriptions FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Los usuarios eliminan sus propias suscripciones"
  ON public.push_subscriptions FOR DELETE
  USING (auth.uid() = user_id);

-- 2. RPC: suscribir un dispositivo (INSERT o UPDATE si ya existe el endpoint)
CREATE OR REPLACE FUNCTION public.push_subscribe(
  p_user_id  uuid,
  p_endpoint text,
  p_p256dh   text,
  p_auth     text,
  p_platform text DEFAULT 'other'
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  INSERT INTO public.push_subscriptions (user_id, endpoint, p256dh, auth, platform)
  VALUES (p_user_id, p_endpoint, p_p256dh, p_auth, p_platform)
  ON CONFLICT (user_id, endpoint)
  DO UPDATE SET p256dh = EXCLUDED.p256dh,
                auth = EXCLUDED.auth,
                platform = EXCLUDED.platform,
                updated_at = now();
  RETURN true;
EXCEPTION WHEN OTHERS THEN
  RETURN false;
END;
$$;

-- 3. RPC: cancelar suscripción de un usuario (todas sus suscripciones)
CREATE OR REPLACE FUNCTION public.push_unsubscribe(
  p_user_id uuid
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  DELETE FROM public.push_subscriptions WHERE user_id = p_user_id;
  RETURN true;
EXCEPTION WHEN OTHERS THEN
  RETURN false;
END;
$$;

-- 4. RPC: obtener todas las suscripciones de un usuario (para el Edge Function)
-- Esta función la usa el backend con service_role, no el frontend.
CREATE OR REPLACE FUNCTION public.push_get_for_user(
  p_user_id uuid
) RETURNS TABLE(
  endpoint   text,
  p256dh     text,
  auth       text,
  platform   text
)
LANGUAGE sql SECURITY DEFINER
SET search_path = 'public'
AS $$
  SELECT ps.endpoint, ps.p256dh, ps.auth, ps.platform
  FROM public.push_subscriptions ps
  WHERE ps.user_id = p_user_id;
$$;
