-- ─────────────────────────────────────────────────────────────────────────────
-- 166_device_tokens_apns.sql — Tokens de dispositivo para push NATIVO
--
-- POR QUÉ UNA TABLA APARTE Y NO push_subscriptions
-- push_subscriptions guarda suscripciones de WEB PUSH: endpoint, p256dh y auth,
-- las tres NOT NULL. El push nativo de iOS/Android no tiene ninguna de esas: es
-- un token opaco de APNs o FCM. Meterlo ahí obligaría a aflojar constraints de
-- una tabla que hoy funciona en producción, o a guardar valores basura.
--
-- POR QUÉ HACE FALTA
-- Web Push necesita un Service Worker, y WKWebView no lo permite salvo que la
-- app declare WKAppBoundDomains. O sea: dentro de la app nativa, Web Push NUNCA
-- va a funcionar. Las notificaciones locales que hay hoy (notifyUser) solo se
-- disparan con la app ABIERTA, porque las maneja React. Un lead nuevo a las
-- 11pm con la app cerrada no avisa a nadie. Esto lo resuelve.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.device_tokens (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token       text NOT NULL,
  platform    text NOT NULL CHECK (platform IN ('ios', 'android')),
  -- Distingue producción de desarrollo: un token sacado con la app de Xcode
  -- vive en el APNs sandbox y el de producción lo rechaza. Sin esto, los
  -- envíos fallan con BadDeviceToken y cuesta entender por qué.
  entorno     text NOT NULL DEFAULT 'production' CHECK (entorno IN ('production', 'sandbox')),
  app_version text,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now(),
  UNIQUE (user_id, token)
);

CREATE INDEX IF NOT EXISTS device_tokens_user_idx ON public.device_tokens (user_id);

ALTER TABLE public.device_tokens ENABLE ROW LEVEL SECURITY;

-- Cada usuario administra únicamente sus propios dispositivos.
DROP POLICY IF EXISTS device_tokens_propios ON public.device_tokens;
CREATE POLICY device_tokens_propios ON public.device_tokens
  FOR ALL TO authenticated
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- El envío corre con service_role desde la Edge Function, que salta RLS.
-- No se le da acceso a `anon` a propósito: un token filtrado permite
-- mandarle notificaciones al teléfono de un asesor.
REVOKE ALL ON public.device_tokens FROM anon;

COMMENT ON TABLE public.device_tokens IS
  'Tokens de APNs/FCM para push nativo. Web Push vive en push_subscriptions: son mecanismos distintos y no se mezclan.';
